[CmdletBinding()]
param(
    [ValidateSet('api', 'websockets')]
    [string]$Scenario = 'api',
    [int]$Vus = 10,
    [int]$Users = 0,
    [string]$Duration = '30s',
    [switch]$KeepEnvironment
)

$ErrorActionPreference = 'Stop'
$project = 'oblix-loadtest'
$compose = Join-Path $PSScriptRoot '..\docker-compose.loadtest.yml'
$script = if ($Scenario -eq 'api') { '/scripts/api-sync.js' } else { '/scripts/websockets.js' }
if ($Users -le 0) { $Users = $Vus }

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    throw 'Docker Desktop is required. Install/start it, then rerun this script.'
}

try {
    docker compose -p $project -f $compose up -d --build --wait api
    if ($LASTEXITCODE -ne 0) { throw 'The isolated Oblix load-test stack did not become healthy.' }

    docker compose -p $project -f $compose --profile tools run --rm `
        -e "VUS=$Vus" -e "USER_COUNT=$Users" -e "DURATION=$Duration" k6 run $script
    if ($LASTEXITCODE -ne 0) { throw 'The load test failed or its thresholds were exceeded.' }
}
finally {
    if (-not $KeepEnvironment) {
        # This destroys the dedicated load-test Postgres volume. Every account,
        # session, note, and sync row generated by this run is deleted here.
        docker compose -p $project -f $compose down --volumes --remove-orphans
    }
}
